### ISSUE TITLE
SPIRegisterInterface.connect_to_resource fails

### ISSUE THREAD

**Issue by bl0x** [amaranth-community-unofficial/amaranth-library#16] opened 2023-04-16 22:17 UTC
When calling `connect_to_resource` on a SPIRegisterInterface (and probably also on the other SPI*Interface:s), I get the following error:

```
AttributeError: 'SPIRegisterInterface' object has no attribute 'spi_bus_out'
```

This appears to be something left over and not tested so far?

**Comment by hansfbaier** [comment] 2023-04-16 22:24
Yes, not tested so far. In total the SPI core needs a rewrite.
It does not perform well, has other issues and should be replaced by a core which does not sample the SPI clock,
but uses the SPI clock to sample the input signal.

**Comment by bl0x** [comment] 2023-04-16 22:32
Yay! And here I was naive and full of hope to just be able to plug and play =)
Is there an example where the SPIRegisterInterface is used (not a test case)?

**Comment by bl0x** [comment] 2023-04-16 22:40
Also, when trying to hook up the resource by hand:

```
m.d.comb += resource.cipo.eq(spi_interface.spi.sdo)
```

I get errors like this:

```
Traceback (most recent call last):
  File "/top_t9_gowin.py", line 17, in <module>
    platform.build(TopT9(), do_program=True)
  File "/amaranth/build/plat.py", line 102, in build
    plan = self.prepare(elaboratable, name, **kwargs)
  File "/amaranth/build/plat.py", line 173, in prepare
    fragment._propagate_ports(ports=self.iter_ports(), all_undef_as_ports=False)
  File "/amaranth/hdl/ir.py", line 463, in _propagate_ports
    self._prepare_use_def_graph(parent, level, uses, defs, ios, self)
  File "/amaranth/hdl/ir.py", line 437, in _prepare_use_def_graph
    subfrag._prepare_use_def_graph(parent, level, uses, defs, ios, top)
  File "/amaranth/hdl/ir.py", line 429, in _prepare_use_def_graph
    add_defs(value._lhs_signals())
  File "/amaranth/hdl/ir.py", line 397, in add_defs
    assert defs[sig] is self
AssertionError
```

**Comment by hansfbaier** [comment] 2023-04-16 22:50
@bl0x Do you have the code of this for me to reproduce? Then I could try and come up with a fix.

**Comment by bl0x** [comment] 2023-04-16 23:14
This is very minimal, but shows the error:

```python

from amaranth import *
from amaranth.build import *
from amaranth_boards.arty_a7 import *
from amaranth_boards.resources import *

from amlib.io.spi import SPIRegisterInterface, SPIDeviceBus

class Top(Elaboratable):

    def __init__(self):
        pass

    def elaborate(self, platform):
        m = Module()

        spi = SPIRegisterInterface(address_size=8, register_size=16,
                                   default_read_value=0xaffe)
        spi_test0 = Signal(16)
        spi_test1 = Signal(16)
        spi.add_register(1, value_signal=spi_test0)
        spi.add_register(2, value_signal=spi_test1)
        spi_res = platform.request('spi', 1)

        # connect spi
        m.d.comb += [
            spi.spi.cs.eq(spi_res.cs),
            spi.spi.sck.eq(spi_res.clk),
            spi.spi.sdi.eq(spi_res.copi),
            spi_res.cipo.eq(spi.spi.sdo)
        ]

        return m

if __name__ == "__main__":
    platform = ArtyA7_35Platform()
    platform.add_resources([
        SPIResource("spi", 1,
            cs_n="0", clk="1", copi="2", cipo="3", conn=("pmod", 0),
            attrs=Attrs(IOSTANDARD="LVCMOS33")
        )
    ])
    platform.build(Top())

```

**Comment by hansfbaier** [comment] 2023-04-17 02:22
@bl0x This was missing
![image](https://user-images.githubusercontent.com/148607/232362958-6c430c14-e66e-4521-be30-c94b7dd488ee.png)
Otherwise it tries to wire it up the wrong way and the error message of amaranth,
regrettably, is anything but user friendly.
So I think this is an amaranth, not an amlib issue.
After that I still get a connector resolving error, but this also seems to be an amaranth issue.
You could try to work around that by referring to individual pins, not the connector.

**Comment by hansfbaier** [comment] 2023-04-17 02:28
@bl0x Ah, no, the numbering needs to be one-based, not zero based, like this:
![image](https://user-images.githubusercontent.com/148607/232363582-46c4c199-7c09-4f95-9e62-2bd2e79104c1.png)
Then the build started to run for me.
More importantly, you might ask, how I found that out.
I placed a strategic 
```
import pdb; pdb.set_trace()
```
at the lines mentioned in the stack trace and then looked around with the pdb.
![image](https://user-images.githubusercontent.com/148607/232363985-661aa13d-99d0-4405-abe5-b0c84b2a764b.png)
I got a `dir(mapping)` and noticed the indices of the pmod connectors started with 1, not 0.

**Comment by hansfbaier** [comment] 2023-04-17 02:32
Closing this also, please report the issue to amaranth/amaranth_boards.
Feel free to reopen, if I left something important unaddressed.

**Closed as completed by hansfbaier** 2023-04-17 02:32 UTC

**Comment by bl0x** [comment] 2023-04-17 05:59
Thanks a lot Hans,

I did not know about the 'role' attribute.
Perhaps it would be nicer to have 'role' without default value to force the user to explicitly state it?

And for pin numbering in my actual code (non-mve) the numbers are 1 based (but I'm using some other higher Pin numbers anyways).

**Comment by hansfbaier** [comment] 2023-04-17 06:19
I did not know about the role attribute either before this :).
I really appreciate the Ctrl-Click navigation in vscodium, it helps me a lot
to figure things out quickly.
That would be a ticket for amaranth_boards, I guess.
Nice to see it works for you.

**Comment by bl0x** [comment] 2023-04-18 12:44
@hansfbaier 
I added the `role="peripheral"` and had to change my connection to this in order to get no complaints from Amaranth:

```python
        # connect spi                                                           
        m.d.comb += [                                                           
            spi.spi.cs.eq(spi_res.cs),                                          
            spi.spi.sck.eq(spi_res.clk),                                        
            spi_res.cipo.eq(spi.spi.sdo),                                       
            spi.spi.sdi.eq(spi_res.copi)                                        
        ]     
```

Should I make a PR with appropriate changes?

**Comment by hansfbaier** [comment] 2023-04-18 12:46
Yes please! Thanks!
